import { User } from '../interfaces/User.interface';

export const userList: User[] = [
  {
    avatar: '/assets/img/avatar2.png',
    createdAt: '',
    email: '',
    fullName: 'Jerome Bell',
    id: '1',
    updatedAt: '',
  },
  {
    avatar: '/assets/img/avatar3.png',
    createdAt: '',
    email: '',
    fullName: 'Robert Fox',
    id: '2',
    updatedAt: '',
  },
  {
    avatar: '/assets/img/avatar4.png',
    createdAt: '',
    email: '',
    fullName: 'Marvin McKinney',
    id: '3',
    updatedAt: '',
  },
  {
    avatar: '/assets/img/avatar5.png',
    createdAt: '',
    email: '',
    fullName: 'Jone Cooper',
    id: '4',
    updatedAt: '',
  },
  {
    avatar: '/assets/img/avatar6.png',
    createdAt: '',
    email: '',
    fullName: 'Ralph Edwards',
    id: '5',
    updatedAt: '',
  },
  {
    avatar: '/assets/img/avatar7.png',
    createdAt: '',
    email: '',
    fullName: 'Wade Warren',
    id: '6',
    updatedAt: '',
  },
  {
    avatar: '/assets/img/avatar8.png',
    createdAt: '',
    email: '',
    fullName: 'Savannah Nguyen',
    id: '7',
    updatedAt: '',
  },
];
